name: Flutter CI/CD

on:
  push:
    branches: ["development", "main"]
  pull_request:
    branches: ["development", "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.3"
          channel: "stable"

      - name: Run package get
        run: |
          cd client
          flutter pub get
      - name: Analyze
        run: |
          cd client
          flutter analyze
